"""Stable error codes shared with FE according to Self_Dev_Docs v2."""

from typing import Any


class DomainError(Exception):
    def __init__(self, code: str, message: str, status_code: int = 400, details: Any = None) -> None:
        super().__init__(message)
        self.code = code
        self.message = message
        self.status_code = status_code
        self.details = details


AUTH_REQUIRED = "AUTH_REQUIRED"
AUTH_TOKEN_MISSING = AUTH_REQUIRED
AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID"
AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
AUTH_SERVICE_UNAVAILABLE = "AUTH_SERVICE_UNAVAILABLE"
AUTH_PROFILE_INVALID = "AUTH_PROFILE_INVALID"
USER_INACTIVE = "USER_INACTIVE"
FORBIDDEN = "FORBIDDEN"
UNIT_NOT_FOUND = "UNIT_NOT_FOUND"
ACCOUNT_ALREADY_BOUND = "ACCOUNT_ALREADY_BOUND"
NO_ACTIVE_UNIT = "NO_ACTIVE_UNIT"
TEXT_OR_IMAGE_REQUIRED = "TEXT_OR_IMAGE_REQUIRED"
IMAGE_UNREADABLE = "IMAGE_UNREADABLE"
INVALID_LOCATION = "INVALID_LOCATION"
TICKET_NOT_FOUND = "TICKET_NOT_FOUND"
TICKET_NOT_OWNED = "TICKET_NOT_OWNED"
INVALID_STATUS_TRANSITION = "INVALID_STATUS_TRANSITION"
P0_REVIEW_REQUIRED = "P0_REVIEW_REQUIRED"
CATEGORY_REQUIRED = "CATEGORY_REQUIRED"
OVERRIDE_REASON_REQUIRED = "OVERRIDE_REASON_REQUIRED"
CONFLICT_VERSION = "CONFLICT_VERSION"
ATTACHMENT_NOT_FOUND = "ATTACHMENT_NOT_FOUND"
INVALID_ATTACHMENT = "INVALID_ATTACHMENT"
INFORMATION_REQUEST_NOT_FOUND = "INFORMATION_REQUEST_NOT_FOUND"
STORAGE_NOT_CONFIGURED = "STORAGE_NOT_CONFIGURED"
DATABASE_NOT_CONFIGURED = "DATABASE_NOT_CONFIGURED"
VALIDATION_ERROR = "VALIDATION_ERROR"
INTERNAL_ERROR = "INTERNAL_ERROR"
